Repository openshift/svt, pull requests merged in 2018-11, with the labels that each got.

#535 Add statefulset config for golang cluster loader
  openshift_scalability/config/golang/statefulset.yaml
Labels: lgtm, size/S

#536 Add durations for individual builds
  openshift_performance/ose3_perf/scripts/build_test.py
Labels: lgtm, size/XS

#537 Updated aos-ansible hosts template to set correct registry folder name when pre-pulling images from registry.reg-aws to support ocp v4 and remain backwards compatible with OCP v3
  image_provisioner/playbooks/roles/aos-ansible/templates/hosts.j2
Labels: size/XS
