Repository openshift/svt, pull requests merged in 2018-12, with the labels that each got.

#541 Always use labeled nodes for pause pods with NV
  openshift_scalability/nodeVertical.sh
Labels: lgtm, size/XS

#544 Golang needs to be fetched from epel.
  openshift_scalability/content/centos-stress/Dockerfile
Labels: size/XS

#545 Add utility to list all CRDs or all resource types
  openshift_tooling/list_all_resources/list_all.py
Labels: lgtm, size/L
