Repository openshift/svt, pull requests merged in 2018-06, with the labels that each got.

#462 Add kraken tool to svt
  openshift_tooling/kraken/README.md
  openshift_tooling/kraken/config/config.ini
  openshift_tooling/kraken/kraken.py
  openshift_tooling/kraken/openshift-templates/hello-openshift.yaml
  openshift_tooling/kraken/requirements.txt
  openshift_tooling/kraken/sample-runs/kill_etcd.png
  openshift_tooling/kraken/sample-runs/kill_master.png
  openshift_tooling/kraken/sample-runs/kill_node.png
  openshift_tooling/kraken/sample-runs/node_crash.png
  openshift_tooling/kraken/sample-runs/node_offline.png
Labels: size/L

#447 [WIP] Add storage test for jenkins
  storage/jenkins/README.md
  storage/jenkins/external_vars.yaml
  storage/jenkins/files/groovy/install_jdk8.groovy
  storage/jenkins/files/groovy/install_mvn339.groovy
  storage/jenkins/files/oc/cm_jjb_template.yaml
  storage/jenkins/files/oc/dc_jjb.yaml
  storage/jenkins/files/oc/jenkins-persistent-template.yaml
  storage/jenkins/files/oc/pvc_template.yaml
  storage/jenkins/files/scripts/create-oc-objects.sh
  storage/jenkins/files/scripts/test-jenkins-m.sh
  storage/jenkins/files/scripts/test-jenkins.sh
  storage/jenkins/files/svt_jobs/defaults.yaml
  storage/jenkins/files/svt_jobs/job-template.yaml
  storage/jenkins/files/svt_jobs/projects.yaml
  storage/jenkins/jenkins-test.yaml
  storage/jenkins/jjb/Dockerfile
  storage/jenkins/jjb/jobs/test.yaml
  storage/jenkins/jjb/requirements.txt
  storage/jenkins/run_jenkins.sh
  storage/jenkins/templates/groovy/jenkins_setup_jdk_user.groovy.j2
Labels: size/XL

#459 Add git workload for storage test
  storage/git/Dockerfile
  storage/git/external_vars.yaml
  storage/git/files/oc/template_git.yaml
  storage/git/files/scripts/create-oc-objects.sh
  storage/git/files/scripts/pbench-register.sh
  storage/git/files/scripts/test-git-m.sh
  storage/git/files/scripts/test-git.sh
  storage/git/git-test.yaml
  storage/git/run_git.sh
Labels: size/L

#458 updates for mongo ycsb scripts
  storage/mongodb/README.md
  storage/mongodb/external_vars.yaml
  storage/mongodb/files/scripts/test-mongo.sh
  storage/mongodb/mongodb-test.yaml
  storage/mongodb/runmongo.sh
Labels: lgtm, size/L

#468 Added pre-3.10 kraken source code, README, and config files
  openshift_tooling/kraken/OpenShift-labeler/README.md
  openshift_tooling/kraken/OpenShift-labeler/label.yaml
  openshift_tooling/kraken/OpenShift-labeler/sample-inventory
  openshift_tooling/kraken/README.md
  openshift_tooling/kraken/config/config.ini
  openshift_tooling/kraken/images/kill_etcd.png
  openshift_tooling/kraken/images/kill_master.png
  openshift_tooling/kraken/images/kill_node.png
  openshift_tooling/kraken/images/node_crash.png
  openshift_tooling/kraken/images/node_offline.png
  openshift_tooling/kraken/kraken.py
  openshift_tooling/kraken/openshift-templates/hello-openshift.yaml
  openshift_tooling/kraken/requirements.txt
Labels: size/XL

#466 Update storage/cns_usability/README.md
  storage/cns_usability/README.md
Labels: size/S

#452 Add ifexists field to master vert configs
  openshift_scalability/config/golang/pyconfigMasterVertScale.yaml
  openshift_scalability/config/golang/pyconfigMasterVertScalePause.yaml
Labels: size/XS

#461 Bake in github token needed to upload scale-ci results
  image_provisioner/inventory/hosts.AWS
  image_provisioner/inventory/hosts.BM
  image_provisioner/inventory/hosts.OS
  image_provisioner/playbooks/roles/os-kickstart/tasks/main.yaml
Labels: size/S

#465 Create new branch with R2R wedge if it doesn't exist already
  utils/pbwedge/main.yml
Labels: size/S

#470 Added a way to just very apps
  reliability/testCluster.sh
Labels: size/XS

#472 Add podvertical scale test
  openshift_scalability/config/cluster-limits-pods-per-namespace.yaml
  openshift_scalability/config/golang/cluster-limits-pods-per-namespace.yaml
  openshift_scalability/podVertical.sh
Labels: size/M

#474 pbwedge pretty print json before commit
  utils/pbwedge/main.yml
Labels: lgtm, size/XS

#473 Modify master vertical test to use a different config
  openshift_scalability/masterVertical.sh
Labels: size/XS

#469 Label pbench nodes in Jenkins test
  storage/git/git-test.yaml
  storage/jenkins/files/scripts/pbench-register.sh
  storage/jenkins/jenkins-test.yaml
Labels: size/M

#471 add simple stress tests
  openshift_scalability/config/golang/stress-simple.yaml
  openshift_scalability/content/pod-stress-simple.json
Labels: size/M

#457 Add support for nodevertical to schedule pods on labeled nodes
  openshift_scalability/config/golang/nodeVertical-labeled-nodes.yaml
  openshift_scalability/content/pod-pause-labeled-nodes.json
  openshift_scalability/nodeVertical.sh
Labels: size/L

#479 Update node labeling on svt openshift_scalability CI scripts for 3.10 and pod limits to stay under 250 per node
  openshift_scalability/ci/scripts/pbench-controller-start-node-vertical.sh
  openshift_scalability/ci/scripts/pbench-start-create-loaded-projects.sh
  openshift_scalability/ci/scripts/run-node-affinity-anti-affinity.sh
  openshift_scalability/ci/scripts/taint_nodes.sh
  openshift_scalability/config/golang/node-affinity-anti-affinity.yaml
  openshift_scalability/config/golang/node-taints-pod-tolerations.yaml
  openshift_scalability/config/golang/nodeVertical_484_pods.yaml
  openshift_scalability/config/golang/pod-affinity-anti-affinity.yaml
Labels: size/L

#463 Updated kraken.py to handle static pods in control plane for OCP 3.10
  openshift_tooling/kraken/kraken.py
Labels: size/M

#482 Modify max pods per ns test to support multiple iterations
  openshift_scalability/config/cluster-limits-pods-per-namespace.yaml
  openshift_scalability/config/golang/cluster-limits-pods-per-namespace.yaml
  openshift_scalability/podVertical.sh
Labels: size/XS

#481 Modify the max pods per ns test to create 15000 pods
  openshift_scalability/config/cluster-limits-pods-per-namespace.yaml
  openshift_scalability/config/golang/cluster-limits-pods-per-namespace.yaml
Labels: size/S

#467 Make the networking synthetic tests CI friendly.
  networking/synthetic/README.md
  networking/synthetic/network-test.py
  networking/synthetic/pod-ip-test-setup.yaml
  networking/synthetic/start-network-test.sh
  networking/synthetic/svc-ip-test-setup.yaml
Labels: size/L
