Repository openshift/svt, pull requests merged in 2018-08, with the labels that each got.

#509 Update build start regex for 3.11
  image_provisioner/playbooks/roles/os-kickstart/tasks/main.yaml
  openshift_performance/ose3_perf/scripts/build_test.py
Labels: size/S

#511 Add support to install pbench-agent-internal
  image_provisioner/playbooks/roles/pbench-config/tasks/main.yaml
  image_provisioner/playbooks/roles/repo-install/tasks/main.yaml
  image_provisioner/playbooks/roles/repo-install/templates/etc/yum.repos.d/pbench-internal.repo.j2
Labels: size/L

#513 Modify nodevertical cleanup to wait for resources to be deleted
  openshift_scalability/nodeVertical.sh
Labels: size/XS

#514 Convert ansible repo to a template
  image_provisioner/inventory/hosts.AWS
  image_provisioner/inventory/hosts.BM
  image_provisioner/inventory/hosts.OS
  image_provisioner/playbooks/roles/repo-install/tasks/main.yaml
  image_provisioner/playbooks/roles/repo-install/templates/etc/yum.repos.d/rhel7-server-ansible.repo.j2
Labels: do-not-merge/hold, size/S

#515 Override jdk username/password in Jenkins test
  storage/jenkins/run_jenkins.sh
Labels: size/XS

#507 Use pbench status as a separate step in fio test
  storage/fio/README.md
  storage/fio/files/scripts/test-storage.sh
  storage/fio/fio-test.yaml
Labels: size/M

#512 Better readme for cns usability tests
  storage/cns_usability/README.md
Labels: size/XS

#504 Extend the prometheus ci scale tests.
  openshift_scalability/ci/scripts/prometheus/prometheus-loader.sh
  openshift_scalability/ci/scripts/prometheus/sanity-period-performance.sh
  openshift_scalability/ci/scripts/prometheus/sanity-stepping-performance.sh
Labels: size/M

#508 Dynamic loader
  openshift_scalability/ci/scripts/prometheus/__init__.py
  openshift_scalability/ci/scripts/prometheus/loaddashboards.py
  openshift_scalability/ci/scripts/prometheus/prometheus-loader.py
  openshift_scalability/ci/scripts/prometheus/prometheus-loader.sh
  openshift_scalability/ci/scripts/prometheus/sanity-period-performance.sh
  openshift_scalability/prometheus-loader.py
Labels: do-not-merge/hold, size/XL

#516 Output result for each project and iteration in git test
  storage/git/external_vars.yaml
  storage/git/files/scripts/test-git.sh
Labels: size/S
