Repository openshift/svt, pull requests merged in 2018-09, with the labels that each got.

#517 Add redis storage test
  storage/redis/external_vars.yaml
  storage/redis/files/oc/dc_ycsb.yaml
  storage/redis/files/oc/redis-persistent-template.yaml
  storage/redis/files/scripts/test-redis-m.sh
  storage/redis/files/scripts/test-redis.sh
  storage/redis/redis-test.yaml
  storage/redis/run_redis.sh
Labels: size/L

#494 Add storage test for amq
  storage/amq/Dockerfile
  storage/amq/amq-test.yaml
  storage/amq/external_vars.yaml
  storage/amq/files/oc/amq63-persistent-template.yaml
  storage/amq/files/oc/dc_amq_perf.yaml
  storage/amq/files/scripts/create-oc-objects.sh
  storage/amq/files/scripts/pbench-register.sh
  storage/amq/files/scripts/test-amq-m.sh
  storage/amq/files/scripts/test-amq.sh
  storage/amq/run_amq.sh
Labels: size/XL

#518 Add loop control when creating oc objects in redis test
  storage/redis/redis-test.yaml
Labels: size/XS

#521 Pull YCSB image for image provisioner
  image_provisioner/playbooks/roles/pbench-kickstart/tasks/main.yml
Labels: size/XS

#506 Use the default config if not defined by the user in podvertical
  openshift_scalability/podVertical.sh
Labels: size/XS

#503 Increased wait timeouts for mongodb/ycsb pods
  storage/mongodb/mongodb-test.yaml
Labels: lgtm, size/S

#523 Updated role os-kickstart to always installs pbench-agent-internal and also install python-boto package
  image_provisioner/playbooks/roles/os-kickstart/tasks/main.yaml
Labels: size/XS

#522 Ignore templating
  openshift_scalability/ci/scripts/prometheus/loaddashboards.py
  openshift_scalability/ci/scripts/prometheus/prometheus-loader.py
  openshift_scalability/ci/scripts/prometheus/prometheus-loader.sh
Labels: size/M

#524 Updated the OpenShift quickstart dancer-mysql templates to the latest version from OCP 3.11.3-1
  openshift_scalability/content/quickstarts/dancer/dancer-build.json
  openshift_scalability/content/quickstarts/dancer/dancer-mysql-deploy.json
  openshift_scalability/content/quickstarts/dancer/dancer-mysql-pv-deploy.json
  openshift_scalability/content/quickstarts/dancer/dancer-mysql-pv.json
  openshift_scalability/content/quickstarts/dancer/dancer-mysql.json
Labels: size/XXL

#525 Updated build_ami.yaml to append the openshift_version string to ami builder instance name
  image_provisioner/playbooks/build_ami.yaml
Labels: size/XS

#520 Add --raw option with no prefix
  openshift_scalability/content/logtest/ocp_logtest-README.md
  openshift_scalability/content/logtest/root/ocp_logtest.py
Labels: size/M

#527 Fix rm_time in storage test for git
  storage/git/files/scripts/test-git.sh
Labels: size/XS

#528 Improvements to intermediate mode
  networking/synthetic/README.md
  networking/synthetic/node-ip-test-setup.yaml
  networking/synthetic/pod-ip-test-setup.yaml
  networking/synthetic/start-network-test.sh
  networking/synthetic/svc-ip-test-setup.yaml
  networking/synthetic/uperf/Dockerfile
Labels: size/L
