Repository openshift/svt, pull requests merged in 2018-07, with the labels that each got.

#475 Introduce a prometheus loader tool.
  openshift_scalability/PrometheusLoader.md
  openshift_scalability/ci/scripts/prometheus-loader.sh
  openshift_scalability/content/prometheus/qs.txt
  openshift_scalability/prometheus-loader.py
Labels: size/L

#483 Add cluster limits namespaces per cluster scale test
  openshift_scalability/cluster-limits-namespaces.sh
  openshift_scalability/config/cluster-limits-namespaces.yaml
  openshift_scalability/config/golang/cluster-limits-namespaces.yaml
  openshift_scalability/content/deployment-config-ns-per-cluster-template.json
Labels: size/L

#480 Add deployments per namespace cluster limit test
  openshift_scalability/config/cluster-limits-deployments-per-namespace.yaml
  openshift_scalability/config/golang/cluster-limits-deployments-per-namespace.yaml
  openshift_scalability/content/deployment-config-cluster-limits-deployments.json
  openshift_scalability/deployments_per_ns.sh
Labels: do-not-merge/hold, size/L

#484 Minor fixes in template and nodevertical script
  openshift_scalability/content/deployment-config-cluster-limits-deployments.json
  openshift_scalability/nodeVertical.sh
Labels: size/XS

#488 Query duration log.
  openshift_scalability/prometheus-loader.py
Labels: size/XS

#490 Fix name of config file to edit. Fixes #489
  openshift_scalability/content/logtest/ocp_logtest-README.md
Labels: size/XS

#491 prometheus stats and tool updates.
  openshift_scalability/ci/scripts/prometheus-loader.sh
  openshift_scalability/prometheus-loader.py
Labels: size/M

#487 Avoid updating microcode_ctl package
  image_provisioner/playbooks/roles/os-kickstart/tasks/main.yaml
Labels: size/XS

#486 Disable host key checking in fio script
  storage/fio/files/scripts/drop-cache.sh
Labels: size/XS

#476 Separate time calculation in Git test
  storage/git/external_vars.yaml
  storage/git/files/scripts/create-oc-objects.sh
  storage/git/files/scripts/test-git.sh
  storage/git/git-test.yaml
  storage/jenkins/external_vars.yaml
  storage/jenkins/files/oc/dc_jjb.yaml
  storage/jenkins/files/oc/pvc_template.yaml
  storage/jenkins/files/scripts/create-oc-objects.sh
  storage/jenkins/jenkins-test.yaml
Labels: size/L

#478 Add support to install crio rpm and needed tools
  image_provisioner/inventory/hosts.AWS
  image_provisioner/inventory/hosts.BM
  image_provisioner/inventory/hosts.OS
  image_provisioner/playbooks/build_ami.yaml
  image_provisioner/playbooks/provision_gold_images.yaml
  image_provisioner/playbooks/roles/aos-ansible/tasks/main.yaml
  image_provisioner/playbooks/roles/cri-o/tasks/main.yml
  image_provisioner/playbooks/roles/docker-config/tasks/main.yaml
  image_provisioner/playbooks/roles/os-kickstart/tasks/main.yaml
  image_provisioner/playbooks/roles/pbench-kickstart/tasks/main.yml
Labels: size/L

#493 logs dir and collectors updata
  openshift_scalability/ci/scripts/prometheus-loader.sh
  openshift_scalability/prometheus-loader.py
Labels: size/M

#498 Fix for multi master environment
  networking/synthetic/start-network-test.sh
Labels: size/S

#497 Conformance wrapper updates for 3.11
  conformance/svt_conformance.sh
Labels: size/XS

#501 Update regex for retrieving build name
  openshift_performance/ose3_perf/scripts/build_test.py
Labels: size/XS

#499 Add pytimeparse for build_test automation
  image_provisioner/playbooks/roles/os-kickstart/tasks/main.yaml
Labels: size/XS

#505 podVertical config abstraction.
  openshift_scalability/podVertical.sh
Labels: size/S
