Repository openshift/svt, pull requests merged in 2019-03, with the labels that each got.

#552 Add configmap template
  openshift_scalability/content/configmap-template.json
Labels: size/M

#558 Remove parameter flag logic for master - only applies to the pre-3.10…
  openshift_scalability/utils.py
Labels: lgtm, size/XS

#557 Prometheus loader update
  openshift_scalability/ci/scripts/prometheus/prometheus-loader.py
  openshift_scalability/ci/scripts/prometheus/prometheus-loader.sh
  openshift_scalability/ci/scripts/prometheus/sanity-period-performance.sh
  openshift_scalability/ci/scripts/prometheus/sanity-stepping-performance.sh
  openshift_scalability/config/golang/stress-simple.yaml
  openshift_scalability/content/pod-stress-simple.json
Labels: size/L

#555 Updated eap and tomcat quickstart templates and reliability testClust…
  openshift_scalability/config/all-quickstarts-no-limits.yaml
  openshift_scalability/content/quickstarts/eap/eap71-mysql.json
  openshift_scalability/content/quickstarts/tomcat/jws31-tomcat8-mongodb.json
  reliability/testCluster.sh
Labels: size/XXL

#562 simplify the pbench execution
  openshift_scalability/ci/scripts/prometheus/prometheus-loader.sh
Labels: size/S

#560 prometheus storage monitor
  openshift_scalability/prometheus_storage_usage.sh
Labels: size/S

#563 fix a typo
  openshift_scalability/prometheus_storage_usage.sh
Labels: lgtm, size/XS

#556 Minor fixes in networking test
  networking/synthetic/node-ip-test-setup.yaml
  networking/synthetic/pod-ip-test-setup.yaml
  networking/synthetic/svc-ip-test-setup.yaml
Labels: size/S

#564 template for smallfile test
  openshift_scalability/content/smallfile/smallfile-parameters.yaml
  openshift_scalability/content/smallfile/smallfile-template.json
Labels: size/L

#567 Concurrent jobs creation with configmap
  openshift_performance/ci/content/conc_jobs.yaml
  openshift_performance/ci/scripts/conc_jobs.sh
Labels: size/M

#566 monogdb test updated
  storage/mongodb/files/oc/ycsb_pod.yaml
  storage/mongodb/files/scripts/create-oc-objects.sh
  storage/mongodb/runmongo.sh
Labels: lgtm, size/M

#561 Use exit code from ansible playbook run
  networking/synthetic/network-test.py
Labels: lgtm, needs-ok-to-test, size/S
