Repository openshift/svt, pull requests merged in 2019-10, with the labels that each got.

#590 Test node tuning operator running in daemon mode
  openshift_tooling/node_tuning_operator/node_tuning_operator_daemon_mode.py
Labels: size/M

#616 Improved monitoring, first steps for user support
  reliability/config/activities.md
  reliability/config/simple_reliability.yaml
  reliability/tasks/Monitor.py
  reliability/tasks/Task.py
  reliability/tasks/TaskManager.py
  reliability/tasks/Users.py
Labels: size/L

#617 Updated openshift_scalability/ci/scripts and openshift_performance/ose3_perf/scripts/scale_test.py to support OPC 4.x and
  openshift_performance/ose3_perf/scripts/scale_test.py
  openshift_scalability/ci/scripts/run-node-affinity-anti-affinity.sh
  openshift_scalability/ci/scripts/run-pod-affinity-anti-affinity.sh
  openshift_scalability/ci/scripts/taint_nodes.sh
Labels: size/XS

#618 Updating all test cases to work with latest NTO running as daemon.
  openshift_tooling/node_tuning_operator/README.md
  openshift_tooling/node_tuning_operator/content/tuned-kernel-pid_max.yml
  openshift_tooling/node_tuning_operator/content/tuned-router.yml
  openshift_tooling/node_tuning_operator/node_tuning_operator.py
  openshift_tooling/node_tuning_operator/node_tuning_operator_custom_tuning.py
  openshift_tooling/node_tuning_operator/node_tuning_operator_daemon_mode.py
  openshift_tooling/node_tuning_operator/nto_suite.py
  openshift_tooling/node_tuning_operator/nto_test_core_functionality_is_working.py
  openshift_tooling/node_tuning_operator/nto_test_custom_tuning.py
  openshift_tooling/node_tuning_operator/nto_test_daemon_mode_label_pod.py
  openshift_tooling/node_tuning_operator/nto_test_daemon_mode_remove_pod.py
  openshift_tooling/node_tuning_operator/utils.py
Labels: size/XXL
