Repository openshift/svt, pull requests merged in 2019-09, with the labels that each got.

#611 Added new script to run pod affinity anti-affinity testcase with new golang cluster loader config file pod-affinity.yaml
  openshift_scalability/ci/scripts/run-pod-affinity-anti-affinity.sh
  openshift_scalability/config/golang/pod-affinity.yaml
Labels: size/L

#610 Logtest verification streaming
  logging_metrics_performance/enterprise_logging/utils/logtest_verification/verify_logtest_index.py
Labels: size/M

#609 Default ocp-logtest image location to quay.io
  openshift_scalability/content/logtest/logtest-pod.json
  openshift_scalability/content/logtest/logtest-rc.json
  openshift_scalability/content/logtest/logtest-syslog-rc.json
  openshift_scalability/content/logtest/ocp_logtest-README.md
Labels: size/XS

#591 Verification number of secrets of openshift-cluster-node-tuning-operator
  openshift_tooling/node_tuning_operator/node_tuning_operator.py
Labels: size/S

#613 Updated rails-postgresql and cakephp-mysql quickstart json templates for OCP 4.2
  openshift_scalability/content/quickstarts/cakephp/cakephp-build.json
  openshift_scalability/content/quickstarts/cakephp/cakephp-mysql-pv.json
  openshift_scalability/content/quickstarts/cakephp/cakephp-mysql.json
  openshift_scalability/content/quickstarts/rails/rails-build.json
  openshift_scalability/content/quickstarts/rails/rails-postgresql-pv.json
  openshift_scalability/content/quickstarts/rails/rails-postgresql.json
Labels: size/XXL
