Repository openshift/svt, pull requests merged in 2019-07, with the labels that each got.

#594 Initial commit for documentation.
  README.md
  docs/README.md
  docs/aws/README.md
  docs/aws/troubleshooting.md
  docs/azure/README.md
  docs/ocp/README.md
  docs/ocp/openshift-tests.md
  docs/ocp/storage_class.md
Labels: size/L

#599 Fix logtest nodeselector
  openshift_scalability/content/logtest/logtest-pod.json
  openshift_scalability/content/logtest/logtest-rc.json
  openshift_scalability/content/logtest/logtest-syslog-rc.json
  openshift_scalability/content/logtest/ocp_logtest-README.md
Labels: size/S

#592 New SVT reliability test for OCP 4.x
  reliability/Dockerfile
  reliability/README.md
  reliability/ReliabilityConfig.py
  reliability/analyst/parse-logs.sh
  reliability/awscreds
  reliability/cleanup.sh
  reliability/config/activities.md
  reliability/config/config.yaml
  reliability/config/ocp4.1_config.yaml
  reliability/config/simple_reliability.yaml
  reliability/config/simple_reliability.yaml.bak
  reliability/config/tasks/day
  reliability/config/tasks/hour
  reliability/config/tasks/minute
  reliability/config/tasks/month
  reliability/config/tasks/pre
  reliability/config/tasks/test
  reliability/config/tasks/week
  reliability/config/users.data
  reliability/invokeReliabilityTest.sh
  reliability/lib/ClusterUser.rb
  reliability/lib/Config.rb
  reliability/lib/EnvironmentManager.rb
  reliability/lib/EventControl.rb
  reliability/lib/InstructionExecute.rb
  reliability/lib/Project.rb
  reliability/lib/ProjectTemplate.rb
  reliability/lib/ProjectsManager.rb
  reliability/lib/TaskControl.rb
  reliability/lib/User.rb
  reliability/lib/UsersManager.rb
  reliability/lib/bin/README
  reliability/lib/bin/dockerclear
  reliability/lib/bin/etcd-monitor
  reliability/lib/bin/etcd-monitory.sh
  reliability/lib/bin/master-monitor
  reliability/lib/bin/master-monitory.sh
  reliability/lib/bin/node-monitor
  reliability/lib/bin/node-monitory.sh
  reliability/monitoring-setup.yml
  reliability/relia.rb
  reliability/reliability.py
  reliability/reliabilityTests.sh
  reliability/setup.yml
  reliability/startReliabilityContainer.sh
  reliability/tasks/Apps.py
  reliability/tasks/Pods.py
  reliability/tasks/Projects.py
  reliability/tasks/Singleton.py
  reliability/tasks/Task.py
  reliability/tasks/TaskManager.py
  reliability/tasks/utils/oc.py
  reliability/tasks/utils/utils.py
  reliability/templates/daemonset-pause-test.yaml
  reliability/templates/eap-secret.json
  reliability/templates/ruby-helloworld-sample.json
  reliability/test.py
  reliability/test.rb
  reliability/testCluster.sh
Labels: size/XXL

#596 Remove node labels after each test
  networking/synthetic/pod-ip-test-setup.yaml
  networking/synthetic/svc-ip-test-setup.yaml
Labels: lgtm, size/S

#593 Script to watch for pod state changes
  utils/scripts/pod_spy.py
Labels: size/L

#600 Cleanup content templates
  openshift_scalability/content/build-config-template.json
  openshift_scalability/content/build-template.json
  openshift_scalability/content/deployment-config-0rep-pause-template.json
  openshift_scalability/content/deployment-config-1rep-pause-template.json
  openshift_scalability/content/deployment-config-2rep-pause-template.json
  openshift_scalability/content/image-stream-template.json
  openshift_scalability/content/route-template.json
  openshift_scalability/content/ssh-secret-template.json
Labels: size/L

#601 Initial commit of verify_logtest_index and helper scripts.
  logging_metrics_performance/enterprise_logging/utils/logtest_verification/create_route.sh
  logging_metrics_performance/enterprise_logging/utils/logtest_verification/requirements.txt
  logging_metrics_performance/enterprise_logging/utils/logtest_verification/templates/els_route.yaml
  logging_metrics_performance/enterprise_logging/utils/logtest_verification/verify_logtest_index.py
Labels: size/L

#602 Updated playbook scale_up_complete.yaml and check_app.py to run on OCP 4.x
  openshift_performance/ci/content/scale_up_complete.yaml
  openshift_performance/ose3_perf/scripts/check_app.py
Labels: size/L

#603 Update mysql and PHP ImageStreamTags
  openshift_scalability/content/quickstarts/cakephp/cakephp-build.json
  openshift_scalability/content/quickstarts/cakephp/cakephp-mysql-deploy.json
  openshift_scalability/content/quickstarts/cakephp/cakephp-mysql-pv-deploy.json
  openshift_scalability/content/quickstarts/cakephp/cakephp-mysql-pv.json
  openshift_scalability/content/quickstarts/cakephp/cakephp-mysql.json
  openshift_scalability/content/quickstarts/dancer/dancer-build.json
  openshift_scalability/content/quickstarts/dancer/dancer-mysql-pv.json
  openshift_scalability/content/quickstarts/dancer/dancer-mysql.json
Labels: size/S
