Repository openshift/svt, pull requests merged in 2019-08, with the labels that each got.

#604 Logtest verification tool improvements
  logging_metrics_performance/enterprise_logging/utils/logtest_verification/verify_logtest_index.py
Labels: size/M

#605 Add verbose option to show messages when pulling from search API
  logging_metrics_performance/enterprise_logging/utils/logtest_verification/verify_logtest_index.py
Labels: size/M

#606 support json logs
  openshift_scalability/content/logtest/root/ocp_logtest.py
Labels: lgtm, size/M

#607 Update Dockerfile for ocp-logtest image.
  openshift_scalability/content/logtest/Dockerfile
Labels: lgtm, size/XS
