Repository openshift/svt, pull requests merged in 2019-04, with the labels that each got.

#570 Catch expections when getting BCs
  openshift_performance/ose3_perf/scripts/build_test.py
Labels: lgtm, size/S

#569 Tooling enchancements
  dockerfiles/pbench/controller/run.sh
  openshift_scalability/podVertical.sh
  openshift_templates/performance_monitoring/pbench/pbench-agent-daemonset-masters.yml
  openshift_templates/performance_monitoring/pbench/pbench-agent-daemonset.yml
  openshift_templates/performance_monitoring/scale-ci-controller/controller-job.yml
Labels: size/M

#571 Support git-workload without pbench
  storage/git/README.md
  storage/git/external_vars.yaml
  storage/git/files/scripts/create-oc-objects.sh
  storage/git/git-test.yaml
Labels: size/M

#572 Support jenkins storage test without pbench
  storage/jenkins/files/scripts/test-jenkins.sh
  storage/jenkins/jenkins-test.yaml
Labels: size/S

#559 Python cluster loader apiserver restarts
  openshift_scalability/config/pyconfigMasterVertScalePause.yaml
  openshift_scalability/utils.py
Labels: size/L

#573 Remove the root mount from controller, pbench-agent templates
  openshift_templates/performance_monitoring/pbench/pbench-agent-daemonset-masters.yml
  openshift_templates/performance_monitoring/pbench/pbench-agent-daemonset.yml
  openshift_templates/performance_monitoring/scale-ci-controller/controller-job.yml
Labels: size/S

#575 Add workaround for multi-thread issue in conc. build
  openshift_performance/ose3_perf/scripts/build_test.py
Labels: size/S

#576 Adding resources to job configuration.
  openshift_performance/ci/content/conc_jobs.yaml
Labels: size/XS

#577 Minor fixes, cleanup
  openshift_scalability/cluster-limits-namespaces.sh
  openshift_scalability/deployments_per_ns.sh
  openshift_scalability/masterVertical.sh
  openshift_scalability/nodeVertical.sh
  openshift_scalability/podVertical.sh
  openshift_tooling/pbench/controller.sh
Labels: size/S

#580 Set the controller and pbench image policy to Always
  openshift_templates/performance_monitoring/pbench/pbench-agent-daemonset-masters.yml
  openshift_templates/performance_monitoring/pbench/pbench-agent-daemonset.yml
  openshift_templates/performance_monitoring/scale-ci-controller/controller-job.yml
  openshift_tooling/pbench/controller.sh
  openshift_tooling/prometheus_db_dump/prometheus_dump.sh
Labels: size/S

#578 Add upgrade job ran through scale-ci-ansible
  dockerfiles/pbench/controller/run.sh
Labels: lgtm, size/S

#565 node tuning operator - custom tuning
  openshift_tooling/node_tuning_operator/README.md
  openshift_tooling/node_tuning_operator/node_tuning_operator.py
  openshift_tooling/node_tuning_operator/node_tuning_operator_custom_tuning.py
  openshift_tooling/node_tuning_operator/utils.py
Labels: lgtm, size/XL

#581 conc. build for 3 workers
  openshift_performance/ci/content/conc_builds_cakephp.yaml
  openshift_performance/ci/content/conc_builds_django.yaml
  openshift_performance/ci/content/conc_builds_eap.yaml
  openshift_performance/ci/content/conc_builds_nodejs.yaml
  openshift_performance/ci/content/conc_builds_rails.yaml
  openshift_performance/ci/scripts/conc_builds.sh
Labels: lgtm, size/M

#579 Add missing paranthesis
  networking/synthetic/network-test.py
Labels: lgtm, needs-ok-to-test, size/XS
