Repository openshift/svt, pull requests merged in 2020-03, with the labels that each got.

#634 Super simple random openshift infra pod killer
  utils/scripts/openshift_pod_killer.sh
Labels: size/XS

#628 Update node tuning operator test scripts to work with OCP 4.4
  openshift_tooling/node_tuning_operator/content/tuned-nf-conntrack-max.yml
  openshift_tooling/node_tuning_operator/nto_test_core_functionality_is_working.py
  openshift_tooling/node_tuning_operator/nto_test_custom_tuning.py
  openshift_tooling/node_tuning_operator/nto_test_daemon_mode_label_pod.py
  openshift_tooling/node_tuning_operator/nto_test_daemon_mode_remove_pod.py
Labels: size/L

#631 Storge git test update
  storage/git/README.md
  storage/git/external_vars.yaml
  storage/git/files/scripts/create-oc-objects.sh
  storage/git/files/scripts/pbench-register.sh
  storage/git/files/scripts/test-git-m.sh
  storage/git/git-test.yaml
  storage/git/run_git.sh
Labels: lgtm, size/L

#632 Storage update redis
  storage/redis/external_vars.yaml
  storage/redis/files/scripts/create-oc-objects.sh
  storage/redis/files/scripts/test-redis-m.sh
  storage/redis/files/scripts/test-redis.sh
  storage/redis/run_redis.sh
Labels: size/L
